const List = [
  'Bread',
  'Fonio',
  'Macaroni',
  'Maize',
  'Millet',
  'Rice',
  'Sorghum',
  'Wheat',
  'Cassava',
  'Cocoyam',
  'Potato',
  'Sweet Potato',
  'Taro',
  'Tiger Nut',
  'Water Yam',
  'Yam',
  'African Yam Bean',
  'Bambara Groundnut',
  'Beans',
  'Lentils',
  'Pigeon Pea',
  'Soya Bean',
  'Amaranth Leaves',
  'Baobab Leaves',
  'Green Beans',
  'Cabbage',
  'Carrot',
  'Cassava Leaves',
  'Cowpea Leaves',
  'Cucumber',
  'Drumstick Leaves',
  'Eggplant',
  'Garlic',
  'Jute Leaves',
  'Lettuce',
  'Okra',
  'Onion',
  'Parsley',
  'Peppers',
  'Pumpkin',
  'Roselle Leaves',
  'Spinach',
  'Tamarind Leaves',
  'Taro Leaves',
  'Tomato',
  'Turnip',
  'Vernonia Leaves',
  'Apple',
  'Avocado',
  'Banana',
  'Baobab Fruit',
  'Breadfruit',
  'Cashew Apple',
  'Clementine',
  'Dates',
  'Fig',
  'Grapefruit',
  'Guava',
  'Jujube',
  'Lemon',
  'Mango',
  'Melon',
  'Orange',
  'Papaya',
  'Pineapple',
  'Pomegranate',
  'Plantain',
  'Tamarind',
  'Watermelon',
  'Cashew Nut',
  'Coconut',
  'Colanut',
  'Groundnut',
  'Melon Seeds',
  'Palm Nut Kernel',
  'Roselle Seeds',
  'Sesame Seeds',
  'Shea Nut',
  'Beef',
  'Game Meat',
  'Chicken',
];

// Convert food list to { label, value } format
export const foodList = List.map((food) => ({
  label: food, // Keep original capitalization
  value: food.toLowerCase().replace(/\s+/g, '-'), // Convert to lowercase & replace spaces with hyphens
}));

export const popularFoodList = [
  'rice',
  'bread',
  'chicken',
  'beef',
  'tomato',
  'onion',
  'plantain',
  'yam',
]
